### ISSUE TITLE
A semicolon is required after a class property (43:5)

### ISSUE THREAD

**Issue by niranjanbprajapati** [react-native-component/react-native-smart-badge#1]
I have installed the component but when my application compiles it gives me following error: 

SyntaxError /projectxyz/node_modules/react-native-smart-badge/Badge.js: A semicolon is required after a class property (43:5)

Can you please help me out with this

**Comment by cyqresig** [comment]
Which version of react-native do you use?

**Comment by niranjanbprajapati** [comment]
"react": "0.14.8",
"react-native": "0.21.0",

**Comment by cyqresig** [comment]
I'm sorry. The component does not support the version of react-native under 0.25
